---
# =============================================================================
# Ansible Role: PostgreSQL Backup - Molecule Configuration
# =============================================================================
# This file configures Molecule for testing the PostgreSQL backup role.
# Tests run on Ubuntu/Debian containers with PostgreSQL pre-installed.
#
# Supported distributions (via MOLECULE_DISTRO env var):
#   - ubuntu2204 (Ubuntu 22.04 LTS)
#   - ubuntu2404 (Ubuntu 24.04 LTS)
#   - debian11 (Debian 11 Bullseye)
#   - debian12 (Debian 12 Bookworm)
# =============================================================================

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: pg-backup-${MOLECULE_DISTRO:-ubuntu2404}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
    prepare: prepare.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_facts
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/..:${MOLECULE_EPHEMERAL_DIRECTORY}/roles"
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: "1"

verifier:
  name: ansible
  options:
    verbose: true

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
